# Generated by Django 3.1.7 on 2022-10-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221028_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(choices=[('ENABLED', 'Enabled'), ('DISABLED', 'Disabled')], default='Disabled', max_length=128),
        ),
    ]
