# Generated by Django 3.1.7 on 2022-10-29 05:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221028_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(choices=[('ENABLED', 'Enabled'), ('DISABLED', 'Disabled')], default='DISABLED', max_length=128),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
