# Generated by Django 4.0.3 on 2022-11-01 07:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='wallet',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='api.wallet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='wallet',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='api.wallet'),
            preserve_default=False,
        ),
    ]
